"""
RAVEN DecisionTrace Domain Entity

First-class domain entity detailing the complete decision lifecycle:
EVENT -> STATE -> REVENUE RISK -> ROOT CAUSE -> CANDIDATE ACTIONS -> EXPECTED VALUE -> POLICY -> DECISION -> EXECUTION -> VERIFICATION -> OUTCOME.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any
from pydantic import BaseModel, Field


class DecisionTraceStatus(str, Enum):
    INITIATED = "INITIATED"
    ANALYZED = "ANALYZED"
    POLICY_APPROVED = "POLICY_APPROVED"
    POLICY_BLOCKED = "POLICY_BLOCKED"
    EXECUTED = "EXECUTED"
    VERIFIED = "VERIFIED"
    ESCALATED = "ESCALATED"
    FAILED = "FAILED"


class DecisionTrace(BaseModel):
    """
    DecisionTrace entity capturing complete autonomous decision lineage.
    """

    decision_id: str = Field(..., description="Unique Decision Trace ID, e.g. trace_01H...")
    recovery_opportunity_id: str = Field(..., description="Associated Recovery Opportunity ID")
    merchant_id: str = Field(..., description="Associated Merchant ID")
    customer_id: str = Field(..., description="Associated Customer ID")
    payment_id: str = Field(..., description="Associated Payment ID")
    input_state_snapshot: dict[str, Any] = Field(
        default_factory=dict, description="Reconstructed entity state snapshot at decision time"
    )
    evidence_references: list[str] = Field(
        default_factory=list, description="IDs of FinancialEvent records used as evidence"
    )
    root_cause_result: dict[str, Any] | None = Field(
        None, description="Root Cause Analyst agent output payload"
    )
    candidate_actions: list[dict[str, Any]] = Field(
        default_factory=list, description="Candidate recovery actions generated by Recovery Planner"
    )
    value_estimates: list[dict[str, Any]] = Field(
        default_factory=list, description="Expected value calculations per candidate action"
    )
    policy_evaluations: list[dict[str, Any]] = Field(
        default_factory=list, description="Deterministic Policy Engine rule evaluations"
    )
    selected_action: dict[str, Any] | None = Field(
        None, description="Action selected for execution or escalation"
    )
    policy_token_id: str | None = Field(
        None, description="ID of issued PolicyApprovalToken if approved"
    )
    execution_result: dict[str, Any] | None = Field(
        None, description="Side-effect tool execution result payload"
    )
    verification_result: dict[str, Any] | None = Field(
        None, description="Verification Agent post-action check payload"
    )
    status: DecisionTraceStatus = Field(
        DecisionTraceStatus.INITIATED, description="Lifecycle trace status"
    )
    timestamps: dict[str, str] = Field(
        default_factory=lambda: {"created_at": datetime.now(timezone.utc).isoformat()},
        description="Key lifecycle milestone timestamps ISO 8601 UTC",
    )

    def mark_milestone(self, milestone_name: str) -> None:
        """Appends a UTC ISO 8601 timestamp milestone to trace."""
        self.timestamps[milestone_name] = datetime.now(timezone.utc).isoformat()
